### ISSUE TITLE
Debian 10 (Buster) support

### ISSUE THREAD

**Issue by chrisatrotter** [ontic/ansible-role-kong#3]
Hi,

Will there be support for Debian 10 (Buster)? There seems to be minor differences between Debian 9 (Stretch) and Debian 10 (Buster). I am new to Debian and have little experience in seeing how much work it would be to go from the previous version to the newest.

**Comment by adamdyson** [comment]
Hi @chrisatrotter, I'm more than happy to add support for Debian 10 to this role, however I can only do that once the Kong developers begin releasing pre-built .deb packages. See https://kong.bintray.com/kong-community-edition-deb/dists/ for a full list of available packages.

Doing a quick search I wasn't to find any info as to when they plan on supporting Buster, it might be worth submitting a ticket at https://github.com/Kong/kong to see if it's on their radar.

**Comment by chrisatrotter** [comment]
Hi @adamdyson ,
I was able to install and run kong on Debian 10 (Buster), but it required me to download kong-1.3.*.deb and install the package on the Debian 10 server. The team over at kong have yet to reply if there will be support for Debian 10 (Buster), so I assume we have to still wait a little while for that.

Thank you again for all the help! I hope to hear from you when that update comes 👍
